dimpleflow:
  processing_data_directory: "/path/to/processing_data"
  models_directory: "models"
  reference_pdb: "reference.pdb"
  filtered_xray_csv: "/path/to/filtered_xray.csv"

ligandflow:
  root_dir: "/data"
  models_directory: "models"
  ligand_csv: "ligands.csv"

gather_xray_data:
  data_directory: "/nsls2/data/amx/proposals/"
  sample_name: "ftsz"

exportflow:
  export_data_directory: ""
  pandda_analyse_directory: ""
  export_list: "export-2.txt"
  ground_basename: "pandda-input"
  changed_basename: "pandda-model"
  ensemble_basename: "ensemble-model"
  validate_only: False 

refineflow:
  export_data_directory: ""
  ligand_csv: ""
  basename: "ensemble-model"
  basename_hkl: "pandda-input"
  refinement_program: "refmac"

groupdepflow:
  groupdep_directory: ""
  refinement_csv: ""
  event_csv: ""
  template_cif: "data_template_Xray_GroupDep.20260423.cif"
  ligand_csv: ""
  pandda_input_dir: ""
  pandda_all_datasets_csv: ""
  groupdep_csv: ""
  target_name: "FtsZ"
  spacegroup: "P65"
  poly_entities:
    - id: 1
      num_chains: 2
