import pandas as pd
import os

def generate_refinement_table(
    export_dir: str,
    dataset_csv: str,
    ligand_csv: str,
    basename: str='refine',
    basename_hkl: str='reflections'
):
    """Loop through the pandda.export directory and build a table containing filepaths for refined
    structure and corresponding reflection cifs. Ligand information is included for each crystal,
    because this information is required for each final changed state structure cif."""
    
    result_list = []
    ligand_df = pd.read_csv(ligand_csv)
    dataset_df = pd.read_csv(dataset_csv)
    
    #the most recently modified reflection/structure cif file is considered to be the final file
    
    for d in os.listdir(export_dir):
        data_dir = Path(Path(export_dir) / Path(d))
        refine_cifs = [f for f in data_dir.iterdir() if (basename in f.name and f.is_file() and f.name.endswith('cif'))]
        refine_cifs = sorted(refine_cifs, key=lambda f: f.stat().st_mtime, reverse=True)
        result_dict = {
            "uid": str(uuid.uuid4()),
            "xtal_id": d,
            "refined_structure_file": next((str(f) for f in refine_cifs if basename_hkl not in f.name), None),
            "refined_reflection_file": next((str(f) for f in refine_cifs if basename_hkl in f.name), None),
            "reflection_data_file": dataset_df.loc[dataset_df['xtal_id'] == d, 'filepath'].iloc[0],
            "smiles": ligand_df.loc[ligand_df['xtal_id'] == d, 'smiles'].iloc[0],
            "catalog_id": ligand_df.loc[ligand_df['xtal_id'] == d, 'catalog_id'].iloc[0],
        }
        result_list.append(result_dict) 
    
    df = pd.DataFrame(result_list)
    df.to_csv('test_table1.csv', index=False)
    return df

def generate_event_table(
    export_dir: str,
    pandda_event_csv: str,
    refinement_table_csv: str
):
    """There is a many-to-one relationship between events and xtal_ids in that there can be multiple
    events for a single dataset. Each event has a corresponding BDC-corrected ccp4 map file generated by
    pandda. These separate events are converted into cif blocks and appened to the changed state structure
    factor cif file. Again the pandda.export directory is the ground truth of what is a changed state."""
    
    # left join the refinement table with the pandda inspect event table and filter pertinent information
    # for group deposition
    
    df1 = pd.read_csv(refinement_table_csv)
    df2 = pd.read_csv(pandda_event_csv)
    df2 = df2.rename(columns={'dtag':'xtal_id'})
    df_merged = df1.merge(df2, on='xtal_id', how='left')
    
    result_list = []
    
    for idx, row in df_merged.iterrows():
        try:
            single_export_dir = Path(export_dir) / Path(row['xtal_id'])
            event_map_file = next((str(f) for f in single_export_dir.iterdir() if f.is_file() and f"event_{row['event_idx']}" in f.name and f.name.endswith('ccp4')),None)
        except Exception as e:
            print(f'problem finding event_map file: {e}')
            
        result_dict = {
            'uid': str(uuid.uuid4()),
            'xtal_id': row['xtal_id'],
            'event_idx': row['event_idx'],
            'event_map_file': event_map_file,
            'xtal_uid': row['uid'],
            'x': row['x'],
            'y': row['y'],
            'z': row['z']
            
        }
        
        if row['Ligand Placed'] == True:
            result_list.append(result_dict)

    df = pd.DataFrame(result_list)
    df.to_csv('test_table2.csv')
    return df